// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class Clientes
{
    public int ClienteID { get; set; }

    public string Nombre { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    [JsonIgnore]
    public virtual ICollection<Equipos> Equipos { get; set; } = new List<Equipos>();
    [JsonIgnore]
    public virtual ICollection<Notificaciones> Notificaciones { get; set; } = new List<Notificaciones>();
}