// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class Costos
{
    public int CostoID { get; set; }

    public int? OrdenID { get; set; }

    public string DetalleCosto { get; set; }

    public decimal? Monto { get; set; }

    public virtual OrdenesServicio Orden { get; set; }
}