// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class Empleados
{
    public int EmpleadoID { get; set; }

    public string Nombre { get; set; }

    public string Cargo { get; set; }

    public string Telefono { get; set; }
    [JsonIgnore]
    public virtual ICollection<HistorialServicios> HistorialServicios { get; set; } = new List<HistorialServicios>();
}