// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class Equipos
{
    public int EquipoID { get; set; }

    public int? ClienteID { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public string NumeroSerie { get; set; }

    public virtual Clientes Cliente { get; set; }

    public virtual ICollection<OrdenesServicio> OrdenesServicio { get; set; } = new List<OrdenesServicio>();
}