// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class Estados
{
    public int EstadoID { get; set; }

    public string NombreEstado { get; set; }
    [JsonIgnore]
    public virtual ICollection<OrdenesServicio> OrdenesServicio { get; set; } = new List<OrdenesServicio>();
}