// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class HistorialServicios
{
    public int HistorialID { get; set; }

    public int? OrdenID { get; set; }

    public int? EmpleadoID { get; set; }

    public string DescripcionTrabajo { get; set; }
    [JsonIgnore]
    public virtual Empleados Empleado { get; set; }
    [JsonIgnore]
    public virtual OrdenesServicio Orden { get; set; }
}