// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class Notificaciones
{
    public int NotificacionID { get; set; }

    public int? ClienteID { get; set; }

    public DateTime? FechaEnvio { get; set; }

    public string TipoNotificacion { get; set; }

    public string Detalle { get; set; }
    [JsonIgnore]
    public virtual Clientes Cliente { get; set; }
}