// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CasaRobot.Dominio.Modelo.Entidades;

public partial class OrdenesServicio
{
    public int OrdenID { get; set; }

    public int? EquipoID { get; set; }

    public DateTime? FechaIngreso { get; set; }

    public int? EstadoID { get; set; }

    public string DescripcionProblema { get; set; }

    public DateTime? FechaSalida { get; set; }
    [JsonIgnore]
    public virtual ICollection<Costos> Costos { get; set; } = new List<Costos>();
    [JsonIgnore]
    public virtual Equipos Equipo { get; set; }
    [JsonIgnore]
    public virtual Estados Estado { get; set; }
    [JsonIgnore]
    public virtual ICollection<HistorialServicios> HistorialServicios { get; set; } = new List<HistorialServicios>();
    [JsonIgnore]
    public virtual ICollection<MetodosPago> MetodosPago { get; set; } = new List<MetodosPago>();
}